# Generated by Django 5.0.2 on 2024-04-03 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarks',
            name='post_id',
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='post_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.posts'),
            preserve_default=False,
        ),
    ]
